package JIRA::API::AddFieldBean 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

JIRA::API::AddFieldBean -

=head1 SYNOPSIS

  my $obj = JIRA::API::AddFieldBean->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< fieldId >>

The ID of the field to add.

=cut

has 'fieldId' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);


1;
