package JIRA::API::AttachmentArchiveEntry 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::AttachmentArchiveEntry -

=head1 SYNOPSIS

  my $obj = JIRA::API::AttachmentArchiveEntry->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< abbreviatedName >>

=cut

has 'abbreviatedName' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< entryIndex >>

=cut

has 'entryIndex' => (
    is       => 'ro',
    isa      => Int,
);

=head2 C<< mediaType >>

=cut

has 'mediaType' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< name >>

=cut

has 'name' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< size >>

=cut

has 'size' => (
    is       => 'ro',
    isa      => Int,
);


1;
