package JIRA::API::AvatarUrlsBean 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use Types::Standard qw(Str Bool Num Int Object ArrayRef);
use MooX::TypeTiny;

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< 16x16 >>

The URL of the item's 16x16 pixel avatar.

=cut

has '16x16' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< 24x24 >>

The URL of the item's 24x24 pixel avatar.

=cut

has '24x24' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< 32x32 >>

The URL of the item's 32x32 pixel avatar.

=cut

has '32x32' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< 48x48 >>

The URL of the item's 48x48 pixel avatar.

=cut

has '48x48' => (
    is       => 'ro',
    isa      => Str,
);


1;
