package JIRA::API::BulkProjectPermissions 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::BulkProjectPermissions -

=head1 SYNOPSIS

  my $obj = JIRA::API::BulkProjectPermissions->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< issues >>

List of issue IDs.

=cut

has 'issues' => (
    is       => 'ro',
    isa      => ArrayRef[Int],
);

=head2 C<< permissions >>

List of project permissions.

=cut

has 'permissions' => (
    is       => 'ro',
    isa      => ArrayRef[Str],
    required => 1,
);

=head2 C<< projects >>

List of project IDs.

=cut

has 'projects' => (
    is       => 'ro',
    isa      => ArrayRef[Int],
);


1;
