package JIRA::API::CompoundClause 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::CompoundClause -

=head1 SYNOPSIS

  my $obj = JIRA::API::CompoundClause->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< clauses >>

The list of nested clauses.

=cut

has 'clauses' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
    required => 1,
);

=head2 C<< operator >>

The operator between the clauses.

=cut

has 'operator' => (
    is       => 'ro',
    isa      => Enum[
        "and",
        "or",
        "not",
    ],
    required => 1,
);


1;
