package JIRA::API::ContainerForRegisteredWebhooks 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

JIRA::API::ContainerForRegisteredWebhooks -

=head1 SYNOPSIS

  my $obj = JIRA::API::ContainerForRegisteredWebhooks->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< webhookRegistrationResult >>

A list of registered webhooks.

=cut

has 'webhookRegistrationResult' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
);


1;
