package JIRA::API::CreatedIssues 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::CreatedIssues -

=head1 SYNOPSIS

  my $obj = JIRA::API::CreatedIssues->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< errors >>

Error details for failed issue creation requests.

=cut

has 'errors' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
);

=head2 C<< issues >>

Details of the issues created.

=cut

has 'issues' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
);


1;
