package JIRA::API::CustomFieldContextDefaultValueMultipleVersionPicker 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::CustomFieldContextDefaultValueMultipleVersionPicker -

=head1 SYNOPSIS

  my $obj = JIRA::API::CustomFieldContextDefaultValueMultipleVersionPicker->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< type >>

=cut

has 'type' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< versionIds >>

The IDs of the default versions.

=cut

has 'versionIds' => (
    is       => 'ro',
    isa      => ArrayRef[Str],
    required => 1,
);

=head2 C<< versionOrder >>

The order the pickable versions are displayed in. If not provided, the released-first order is used. Available version orders are `"releasedFirst"` and `"unreleasedFirst"`.

=cut

has 'versionOrder' => (
    is       => 'ro',
    isa      => Str,
);


1;
