package JIRA::API::EntityPropertyDetails 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::EntityPropertyDetails -

=head1 SYNOPSIS

  my $obj = JIRA::API::EntityPropertyDetails->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< entityId >>

The entity property ID.

=cut

has 'entityId' => (
    is       => 'ro',
    isa      => Num,
    required => 1,
);

=head2 C<< key >>

The entity property key.

=cut

has 'key' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< value >>

The new value of the entity property.

=cut

has 'value' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);


1;
