package JIRA::API::ErrorCollection 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::ErrorCollection -

=head1 SYNOPSIS

  my $obj = JIRA::API::ErrorCollection->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< errorMessages >>

The list of error messages produced by this operation. For example, "input parameter 'key' must be provided"

=cut

has 'errorMessages' => (
    is       => 'ro',
    isa      => ArrayRef[Str],
);

=head2 C<< errors >>

The list of errors by parameter returned by the operation. For example,"projectKey": "Project keys must start with an uppercase letter, followed by one or more uppercase alphanumeric characters."

=cut

has 'errors' => (
    is       => 'ro',
    isa      => HashRef,
);

=head2 C<< status >>

=cut

has 'status' => (
    is       => 'ro',
    isa      => Int,
);


1;
