package JIRA::API::FieldChangedClause 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::FieldChangedClause -

=head1 SYNOPSIS

  my $obj = JIRA::API::FieldChangedClause->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< field >>

A field used in a JQL query. See [Advanced searching - fields reference](https://confluence.atlassian.com/x/dAiiLQ) for more information about fields in JQL queries.

=cut

has 'field' => (
    is       => 'ro',
    isa      => HashRef,
    required => 1,
);

=head2 C<< operator >>

The operator applied to the field.

=cut

has 'operator' => (
    is       => 'ro',
    isa      => Enum[
        "changed",
    ],
    required => 1,
);

=head2 C<< predicates >>

The list of time predicates.

=cut

has 'predicates' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
    required => 1,
);


1;
