package JIRA::API::GroupLabel 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::GroupLabel -

=head1 SYNOPSIS

  my $obj = JIRA::API::GroupLabel->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< text >>

The group label name.

=cut

has 'text' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< title >>

The title of the group label.

=cut

has 'title' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< type >>

The type of the group label.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "ADMIN",
        "SINGLE",
        "MULTIPLE",
    ],
);


1;
