package JIRA::API::HealthCheckResult 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::HealthCheckResult -

=head1 SYNOPSIS

  my $obj = JIRA::API::HealthCheckResult->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< description >>

The description of the Jira health check item.

=cut

has 'description' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< name >>

The name of the Jira health check item.

=cut

has 'name' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< passed >>

Whether the Jira health check item passed or failed.

=cut

has 'passed' => (
    is       => 'ro',
);


1;
