package JIRA::API::IssueUpdateMetadata 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::IssueUpdateMetadata -

=head1 SYNOPSIS

  my $obj = JIRA::API::IssueUpdateMetadata->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< fields >>

=cut

has 'fields' => (
    is       => 'ro',
    isa      => HashRef,
);


1;
