package JIRA::API::IssuesMetaBean 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::IssuesMetaBean -

=head1 SYNOPSIS

  my $obj = JIRA::API::IssuesMetaBean->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< jql >>

The description of the page of issues loaded by the provided JQL query.

=cut

has 'jql' => (
    is       => 'ro',
    isa      => HashRef,
);


1;
