package JIRA::API::IssueTypeScreenSchemeMappingDetails 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

JIRA::API::IssueTypeScreenSchemeMappingDetails -

=head1 SYNOPSIS

  my $obj = JIRA::API::IssueTypeScreenSchemeMappingDetails->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< issueTypeMappings >>

The list of issue type to screen scheme mappings. A *default* entry cannot be specified because a default entry is added when an issue type screen scheme is created.

=cut

has 'issueTypeMappings' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
    required => 1,
);


1;
