package JIRA::API::IssueCreateMetadata 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::IssueCreateMetadata -

=head1 SYNOPSIS

  my $obj = JIRA::API::IssueCreateMetadata->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< expand >>

Expand options that include additional project details in the response.

=cut

has 'expand' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< projects >>

List of projects and their issue creation metadata.

=cut

has 'projects' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
);


1;
