package JIRA::API::IssueFieldOptionConfiguration 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::IssueFieldOptionConfiguration -

=head1 SYNOPSIS

  my $obj = JIRA::API::IssueFieldOptionConfiguration->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< attributes >>

DEPRECATED

=cut

has 'attributes' => (
    is       => 'ro',
    isa      => ArrayRef[Str],
);

=head2 C<< scope >>

Defines the projects that the option is available in. If the scope is not defined, then the option is available in all projects.

=cut

has 'scope' => (
    is       => 'ro',
);


1;
