package JIRA::API::IssueFilterForBulkPropertyDelete 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::IssueFilterForBulkPropertyDelete -

=head1 SYNOPSIS

  my $obj = JIRA::API::IssueFilterForBulkPropertyDelete->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< currentValue >>

The value of properties to perform the bulk operation on.

=cut

has 'currentValue' => (
    is       => 'ro',
);

=head2 C<< entityIds >>

List of issues to perform the bulk delete operation on.

=cut

has 'entityIds' => (
    is       => 'ro',
    isa      => ArrayRef[Int],
);


1;
