package JIRA::API::IssueFieldOption 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::IssueFieldOption -

=head1 SYNOPSIS

  my $obj = JIRA::API::IssueFieldOption->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< config >>

Details of the projects the option is available in.

=cut

has 'config' => (
    is       => 'ro',
    isa      => HashRef,
);

=head2 C<< id >>

The unique identifier for the option. This is only unique within the select field's set of options.

=cut

has 'id' => (
    is       => 'ro',
    isa      => Int,
    required => 1,
);

=head2 C<< properties >>

The properties of the object, as arbitrary key-value pairs. These properties can be searched using JQL, if the extractions (see [Issue Field Option Property Index](https://developer.atlassian.com/cloud/jira/platform/modules/issue-field-option-property-index/)) are defined in the descriptor for the issue field module.

=cut

has 'properties' => (
    is       => 'ro',
    isa      => HashRef,
);

=head2 C<< value >>

The option's name, which is displayed in Jira.

=cut

has 'value' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);


1;
