package JIRA::API::JiraExpressionsAnalysis 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

JIRA::API::JiraExpressionsAnalysis -

=head1 SYNOPSIS

  my $obj = JIRA::API::JiraExpressionsAnalysis->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< results >>

The results of Jira expressions analysis.

=cut

has 'results' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
    required => 1,
);


1;
