package JIRA::API::JqlQueryFieldEntityProperty 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::JqlQueryFieldEntityProperty -

=head1 SYNOPSIS

  my $obj = JIRA::API::JqlQueryFieldEntityProperty->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< entity >>

The object on which the property is set.

=cut

has 'entity' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< key >>

The key of the property.

=cut

has 'key' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< path >>

The path in the property value to query.

=cut

has 'path' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< type >>

The type of the property value extraction. Not available if the extraction for the property is not registered on the instance with the [Entity property](https://developer.atlassian.com/cloud/jira/platform/modules/entity-property/) module.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "number",
        "string",
        "text",
        "date",
        "user",
    ],
);


1;
