package JIRA::API::JqlQueryClauseTimePredicate 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

JIRA::API::JqlQueryClauseTimePredicate -

=head1 SYNOPSIS

  my $obj = JIRA::API::JqlQueryClauseTimePredicate->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< operand >>

Details of an operand in a JQL clause.

=cut

has 'operand' => (
    is       => 'ro',
    isa      => HashRef,
    required => 1,
);

=head2 C<< operator >>

The operator between the field and the operand.

=cut

has 'operator' => (
    is       => 'ro',
    isa      => Enum[
        "before",
        "after",
        "from",
        "to",
        "on",
        "during",
        "by",
    ],
    required => 1,
);


1;
