package JIRA::API::JsonContextVariable 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::JsonContextVariable -

=head1 SYNOPSIS

  my $obj = JIRA::API::JsonContextVariable->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< type >>

Type of custom context variable.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< value >>

A JSON object containing custom content.

=cut

has 'value' => (
    is       => 'ro',
    isa      => HashRef,
);


1;
