package JIRA::API::LicensedApplication 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

JIRA::API::LicensedApplication -

=head1 SYNOPSIS

  my $obj = JIRA::API::LicensedApplication->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< id >>

The ID of the application.

=cut

has 'id' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< plan >>

The licensing plan.

=cut

has 'plan' => (
    is       => 'ro',
    isa      => Enum[
        "UNLICENSED",
        "FREE",
        "PAID",
    ],
    required => 1,
);


1;
