package JIRA::API::ListOperand 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::ListOperand -

=head1 SYNOPSIS

  my $obj = JIRA::API::ListOperand->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< encodedOperand >>

Encoded operand, which can be used directly in a JQL query.

=cut

has 'encodedOperand' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< values >>

The list of operand values.

=cut

has 'values' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
    required => 1,
);


1;
