package JIRA::API::MoveFieldBean 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

JIRA::API::MoveFieldBean -

=head1 SYNOPSIS

  my $obj = JIRA::API::MoveFieldBean->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< after >>

The ID of the screen tab field after which to place the moved screen tab field. Required if `position` isn't provided.

=cut

has 'after' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< position >>

The named position to which the screen tab field should be moved. Required if `after` isn't provided.

=cut

has 'position' => (
    is       => 'ro',
    isa      => Enum[
        "Earlier",
        "Later",
        "First",
        "Last",
    ],
);


1;
