package JIRA::API::NestedResponse 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::NestedResponse -

=head1 SYNOPSIS

  my $obj = JIRA::API::NestedResponse->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< errorCollection >>

Error messages from an operation.

=cut

has 'errorCollection' => (
    is       => 'ro',
    isa      => HashRef,
);

=head2 C<< status >>

=cut

has 'status' => (
    is       => 'ro',
    isa      => Int,
);

=head2 C<< warningCollection >>

=cut

has 'warningCollection' => (
    is       => 'ro',
    isa      => HashRef,
);


1;
