package JIRA::API::NotificationSchemeAndProjectMappingJsonBean 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

JIRA::API::NotificationSchemeAndProjectMappingJsonBean -

=head1 SYNOPSIS

  my $obj = JIRA::API::NotificationSchemeAndProjectMappingJsonBean->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< notificationSchemeId >>

=cut

has 'notificationSchemeId' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< projectId >>

=cut

has 'projectId' => (
    is       => 'ro',
    isa      => Str,
);


1;
