package JIRA::API::PermissionHolder 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::PermissionHolder -

=head1 SYNOPSIS

  my $obj = JIRA::API::PermissionHolder->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< expand >>

Expand options that include additional permission holder details in the response.

=cut

has 'expand' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< parameter >>

As a group's name can change, use of `value` is recommended. The identifier associated withthe `type` value that defines the holder of the permission.

=cut

has 'parameter' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< type >>

The type of permission holder.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< value >>

The identifier associated with the `type` value that defines the holder of the permission.

=cut

has 'value' => (
    is       => 'ro',
    isa      => Str,
);


1;
