package JIRA::API::PermissionsKeysBean 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use Types::Standard qw(Str Bool Num Int Object ArrayRef);
use MooX::TypeTiny;

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< permissions >>

A list of permission keys.

=cut

has 'permissions' => (
    is       => 'ro',
    isa      => ArrayRef[Str],
    required => 1,
);


1;
