package JIRA::API::ProjectFeatureState 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::ProjectFeatureState -

=head1 SYNOPSIS

  my $obj = JIRA::API::ProjectFeatureState->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< state >>

The feature state.

=cut

has 'state' => (
    is       => 'ro',
    isa      => Enum[
        "ENABLED",
        "DISABLED",
        "COMING_SOON",
    ],
);


1;
