package JIRA::API::ProjectRoleGroup 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::ProjectRoleGroup -

=head1 SYNOPSIS

  my $obj = JIRA::API::ProjectRoleGroup->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< displayName >>

The display name of the group.

=cut

has 'displayName' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< groupId >>

The ID of the group.

=cut

has 'groupId' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< name >>

The name of the group. As a group's name can change, use of `groupId` is recommended to identify the group.

=cut

has 'name' => (
    is       => 'ro',
    isa      => Str,
);


1;
