package JIRA::API::PublishDraftWorkflowScheme 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::PublishDraftWorkflowScheme -

=head1 SYNOPSIS

  my $obj = JIRA::API::PublishDraftWorkflowScheme->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< statusMappings >>

Mappings of statuses to new statuses for issue types.

=cut

has 'statusMappings' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
);


1;
