package JIRA::API::Scope 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::Scope -

=head1 SYNOPSIS

  my $obj = JIRA::API::Scope->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< project >>

The project the item has scope in.

=cut

has 'project' => (
    is       => 'ro',
);

=head2 C<< type >>

The type of scope.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "PROJECT",
        "TEMPLATE",
    ],
);


1;
