package JIRA::API::SecuritySchemes 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use Types::Standard qw(Str Bool Num Int Object ArrayRef);
use MooX::TypeTiny;

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< issueSecuritySchemes >>

List of security schemes.

=cut

has 'issueSecuritySchemes' => (
    is       => 'ro',
    isa      => ArrayRef[Object],
);


1;
