package JIRA::API::StatusCreateRequest 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::StatusCreateRequest -

=head1 SYNOPSIS

  my $obj = JIRA::API::StatusCreateRequest->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< scope >>

The scope of the status.

=cut

has 'scope' => (
    is       => 'ro',
    isa      => HashRef,
    required => 1,
);

=head2 C<< statuses >>

Details of the statuses being created.

=cut

has 'statuses' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
    required => 1,
);


1;
