package JIRA::API::StatusScope 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::StatusScope -

=head1 SYNOPSIS

  my $obj = JIRA::API::StatusScope->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< project >>

Project ID details.

=cut

has 'project' => (
    is       => 'ro',
    isa      => HashRef,
);

=head2 C<< type >>

The scope of the status. `GLOBAL` for company-managed projects and `PROJECT` for team-managed projects.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "PROJECT",
        "GLOBAL",
    ],
    required => 1,
);


1;
