package JIRA::API::Transitions 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::Transitions -

=head1 SYNOPSIS

  my $obj = JIRA::API::Transitions->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< expand >>

Expand options that include additional transitions details in the response.

=cut

has 'expand' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< transitions >>

List of issue transitions.

=cut

has 'transitions' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
);


1;
