package JIRA::API::UpdateCustomFieldDetails 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use Types::Standard qw(Enum Str Bool Num Int Object ArrayRef);
use MooX::TypeTiny;

=head1 NAME

JIRA::API::UpdateCustomFieldDetails -

=head1 SYNOPSIS

  my $obj = JIRA::API::UpdateCustomFieldDetails->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< description >>

The description of the custom field. The maximum length is 40000 characters.

=cut

has 'description' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< name >>

The name of the custom field. It doesn't have to be unique. The maximum length is 255 characters.

=cut

has 'name' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< searcherKey >>

The searcher that defines the way the field is searched in Jira. It can be set to `null`, otherwise you must specify the valid searcher for the field type, as listed below (abbreviated values shown):

 *  `cascadingselect`: `cascadingselectsearcher`
 *  `datepicker`: `daterange`
 *  `datetime`: `datetimerange`
 *  `float`: `exactnumber` or `numberrange`
 *  `grouppicker`: `grouppickersearcher`
 *  `importid`: `exactnumber` or `numberrange`
 *  `labels`: `labelsearcher`
 *  `multicheckboxes`: `multiselectsearcher`
 *  `multigrouppicker`: `multiselectsearcher`
 *  `multiselect`: `multiselectsearcher`
 *  `multiuserpicker`: `userpickergroupsearcher`
 *  `multiversion`: `versionsearcher`
 *  `project`: `projectsearcher`
 *  `radiobuttons`: `multiselectsearcher`
 *  `readonlyfield`: `textsearcher`
 *  `select`: `multiselectsearcher`
 *  `textarea`: `textsearcher`
 *  `textfield`: `textsearcher`
 *  `url`: `exacttextsearcher`
 *  `userpicker`: `userpickergroupsearcher`
 *  `version`: `versionsearcher`

=cut

has 'searcherKey' => (
    is       => 'ro',
    isa      => Enum[
        "com.atlassian.jira.plugin.system.customfieldtypes:cascadingselectsearcher",
        "com.atlassian.jira.plugin.system.customfieldtypes:daterange",
        "com.atlassian.jira.plugin.system.customfieldtypes:datetimerange",
        "com.atlassian.jira.plugin.system.customfieldtypes:exactnumber",
        "com.atlassian.jira.plugin.system.customfieldtypes:exacttextsearcher",
        "com.atlassian.jira.plugin.system.customfieldtypes:grouppickersearcher",
        "com.atlassian.jira.plugin.system.customfieldtypes:labelsearcher",
        "com.atlassian.jira.plugin.system.customfieldtypes:multiselectsearcher",
        "com.atlassian.jira.plugin.system.customfieldtypes:numberrange",
        "com.atlassian.jira.plugin.system.customfieldtypes:projectsearcher",
        "com.atlassian.jira.plugin.system.customfieldtypes:textsearcher",
        "com.atlassian.jira.plugin.system.customfieldtypes:userpickergroupsearcher",
        "com.atlassian.jira.plugin.system.customfieldtypes:versionsearcher",
    ],
);


1;
