package JIRA::API::UpdateDefaultScreenScheme 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

JIRA::API::UpdateDefaultScreenScheme -

=head1 SYNOPSIS

  my $obj = JIRA::API::UpdateDefaultScreenScheme->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< screenSchemeId >>

The ID of the screen scheme.

=cut

has 'screenSchemeId' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);


1;
