package JIRA::API::VersionUsageInCustomField 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::VersionUsageInCustomField -

=head1 SYNOPSIS

  my $obj = JIRA::API::VersionUsageInCustomField->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< customFieldId >>

The ID of the custom field.

=cut

has 'customFieldId' => (
    is       => 'ro',
    isa      => Int,
);

=head2 C<< fieldName >>

The name of the custom field.

=cut

has 'fieldName' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< issueCountWithVersionInCustomField >>

Count of the issues where the custom field contains the version.

=cut

has 'issueCountWithVersionInCustomField' => (
    is       => 'ro',
    isa      => Int,
);


1;
