package JIRA::API::WebhooksExpirationDate 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use Types::Standard qw(Str Bool Num Int Object ArrayRef);
use MooX::TypeTiny;

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< expirationDate >>

The expiration date of all the refreshed webhooks.

=cut

has 'expirationDate' => (
    is       => 'ro',
    isa      => Int,
    required => 1,
);


1;
