package JIRA::API::WorkflowCompoundCondition 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use Types::Standard qw(Str Bool Num Int Object ArrayRef);
use MooX::TypeTiny;

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< conditions >>

The list of workflow conditions.

=cut

has 'conditions' => (
    is       => 'ro',
    isa      => ArrayRef[Object],
    required => 1,
);

=head2 C<< nodeType >>

=cut

has 'nodeType' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< operator >>

The compound condition operator.

=cut

has 'operator' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);


1;
