package JIRA::API::WorkflowSchemeAssociations 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

JIRA::API::WorkflowSchemeAssociations -

=head1 SYNOPSIS

  my $obj = JIRA::API::WorkflowSchemeAssociations->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< projectIds >>

The list of projects that use the workflow scheme.

=cut

has 'projectIds' => (
    is       => 'ro',
    isa      => ArrayRef[Str],
    required => 1,
);

=head2 C<< workflowScheme >>

The workflow scheme.

=cut

has 'workflowScheme' => (
    is       => 'ro',
    required => 1,
);


1;
