package JIRA::API::WorkflowCompoundCondition 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

JIRA::API::WorkflowCompoundCondition -

=head1 SYNOPSIS

  my $obj = JIRA::API::WorkflowCompoundCondition->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< conditions >>

The list of workflow conditions.

=cut

has 'conditions' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
    required => 1,
);

=head2 C<< nodeType >>

=cut

has 'nodeType' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< operator >>

The compound condition operator.

=cut

has 'operator' => (
    is       => 'ro',
    isa      => Enum[
        "AND",
        "OR",
    ],
    required => 1,
);


1;
