package AI::OpenAI::AssistantsApiResponseFormatOption 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use experimental 'signatures';
use stable 'postderef';
use Carp 'croak';

=encoding utf8

=head1 NAME

AI::OpenAI::AssistantsApiResponseFormatOption - Factory class

=head1 SYNOPSIS

  my $obj = AI::OpenAI::AssistantsApiResponseFormatOption->new($args);
  ...

This is a factory class that returns one of the following types
based on the C<< type >> field:

C<< json_object >> - L<< AI::OpenAI::AssistantsApiResponseFormat >>

C<< text >> - L<< AI::OpenAI::AssistantsApiResponseFormat >>


=cut

use AI::OpenAI::AssistantsApiResponseFormat;


our %classes = (
    'json_object' => 'AI::OpenAI::AssistantsApiResponseFormat',
    'text' => 'AI::OpenAI::AssistantsApiResponseFormat',
);

sub new( $class, $data ) {
    if( ! exists $data->{ 'type' } ) {
        croak "Need a 'type' field";
    };
    my $type = $data->{ 'type' };
    croak "Unknown type '$type' in field 'type'"
        unless exists $classes{ $type };

    return $classes{ $type }->new( $data );
}

1;
