package AI::OpenAI::AssistantToolsFileSearch 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

AI::OpenAI::AssistantToolsFileSearch -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::AssistantToolsFileSearch->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< type >>

The type of tool being defined: `file_search`

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "file_search",
    ],
    required => 1,
);


1;
