package AI::OpenAI::AssistantToolsCode 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::AssistantToolsCode -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::AssistantToolsCode->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< type >>

The type of tool being defined: `code_interpreter`

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "code_interpreter",
    ],
    required => 1,
);


1;
