package AI::OpenAI::ChatCompletionRequestMessageContentPartText 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

AI::OpenAI::ChatCompletionRequestMessageContentPartText -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::ChatCompletionRequestMessageContentPartText->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< text >>

The text content.

=cut

has 'text' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< type >>

The type of the content part.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "text",
    ],
    required => 1,
);


1;
