package AI::OpenAI::ChatCompletionRequestMessageContentPart 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use experimental 'signatures';
use stable 'postderef';
use Carp 'croak';

=encoding utf8

=head1 NAME

AI::OpenAI::ChatCompletionRequestMessageContentPart - Factory class

=head1 SYNOPSIS

  my $obj = AI::OpenAI::ChatCompletionRequestMessageContentPart->new($args);
  ...

This is a factory class that returns one of the following types
based on the C<< type >> field:

C<< image_url >> - L<< AI::OpenAI::ChatCompletionRequestMessageContentPartImage >>

C<< text >> - L<< AI::OpenAI::ChatCompletionRequestMessageContentPartText >>


=cut

use AI::OpenAI::ChatCompletionRequestMessageContentPartImage;
use AI::OpenAI::ChatCompletionRequestMessageContentPartText;


our %classes = (
    'image_url' => 'AI::OpenAI::ChatCompletionRequestMessageContentPartImage',
    'text' => 'AI::OpenAI::ChatCompletionRequestMessageContentPartText',
);

sub new( $class, $data ) {
    if( ! exists $data->{ 'type' } ) {
        croak "Need a 'type' field";
    };
    my $type = $data->{ 'type' };
    croak "Unknown type '$type' in field 'type'"
        unless exists $classes{ $type };

    return $classes{ $type }->new( $data );
}

1;
