package AI::OpenAI::ChatCompletionRequestUserMessage 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::ChatCompletionRequestUserMessage -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::ChatCompletionRequestUserMessage->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< content >>

The contents of the user message.

=cut

has 'content' => (
    is       => 'ro',
    required => 1,
);

=head2 C<< name >>

An optional name for the participant. Provides the model information to differentiate between participants of the same role.

=cut

has 'name' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< role >>

The role of the messages author, in this case `user`.

=cut

has 'role' => (
    is       => 'ro',
    isa      => Enum[
        "user",
    ],
    required => 1,
);


1;
