package AI::OpenAI::ChatCompletionRequestFunctionMessage 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::ChatCompletionRequestFunctionMessage -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::ChatCompletionRequestFunctionMessage->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< content >>

The contents of the function message.

=cut

has 'content' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< name >>

The name of the function to call.

=cut

has 'name' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< role >>

The role of the messages author, in this case `function`.

=cut

has 'role' => (
    is       => 'ro',
    isa      => Enum[
        "function",
    ],
    required => 1,
);


1;
