package AI::OpenAI::ChatCompletionTokenLogprob 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

AI::OpenAI::ChatCompletionTokenLogprob -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::ChatCompletionTokenLogprob->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< bytes >>

A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.

=cut

has 'bytes' => (
    is       => 'ro',
    isa      => ArrayRef[Int],
    required => 1,
);

=head2 C<< logprob >>

The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.

=cut

has 'logprob' => (
    is       => 'ro',
    isa      => Num,
    required => 1,
);

=head2 C<< token >>

The token.

=cut

has 'token' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< top_logprobs >>

List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.

=cut

has 'top_logprobs' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
    required => 1,
);


1;
