package AI::OpenAI::CreateModerationResponse 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::CreateModerationResponse -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::CreateModerationResponse->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< id >>

The unique identifier for the moderation request.

=cut

has 'id' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< model >>

The model used to generate the moderation results.

=cut

has 'model' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< results >>

A list of moderation objects.

=cut

has 'results' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
    required => 1,
);


1;
