package AI::OpenAI::CreateTranscriptionRequest 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::CreateTranscriptionRequest -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::CreateTranscriptionRequest->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< file >>

The audio file object (not file name) to transcribe, in one of these formats: flac, mp3, mp4, mpeg, mpga, m4a, ogg, wav, or webm.

=cut

has 'file' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< language >>

The language of the input audio. Supplying the input language in [ISO-639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) format will improve accuracy and latency.

=cut

has 'language' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< model >>

ID of the model to use. Only `whisper-1` (which is powered by our open source Whisper V2 model) is currently available.

=cut

has 'model' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< prompt >>

An optional text to guide the model's style or continue a previous audio segment. The [prompt](/docs/guides/speech-to-text/prompting) should match the audio language.

=cut

has 'prompt' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< response_format >>

The format of the transcript output, in one of these options: `json`, `text`, `srt`, `verbose_json`, or `vtt`.

=cut

has 'response_format' => (
    is       => 'ro',
    isa      => Enum[
        "json",
        "text",
        "srt",
        "verbose_json",
        "vtt",
    ],
);

=head2 C<< temperature >>

The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. If set to 0, the model will use [log probability](https://en.wikipedia.org/wiki/Log_probability) to automatically increase the temperature until certain thresholds are hit.

=cut

has 'temperature' => (
    is       => 'ro',
    isa      => Num,
);

=head2 C<< timestamp_granularities_ >>

The timestamp granularities to populate for this transcription. `response_format` must be set `verbose_json` to use timestamp granularities. Either or both of these options are supported: `word`, or `segment`. Note: There is no additional latency for segment timestamps, but generating word timestamps incurs additional latency.

=cut

has 'timestamp_granularities_' => (
    is       => 'ro',
    isa      => ArrayRef[Str],
);


1;
