package AI::OpenAI::CreateImageRequest 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

AI::OpenAI::CreateImageRequest -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::CreateImageRequest->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< model >>

The model to use for image generation.

=cut

has 'model' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< n >>

The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.

=cut

has 'n' => (
    is       => 'ro',
    isa      => Int,
);

=head2 C<< prompt >>

A text description of the desired image(s). The maximum length is 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.

=cut

has 'prompt' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< quality >>

The quality of the image that will be generated. `hd` creates images with finer details and greater consistency across the image. This param is only supported for `dall-e-3`.

=cut

has 'quality' => (
    is       => 'ro',
    isa      => Enum[
        "standard",
        "hd",
    ],
);

=head2 C<< response_format >>

The format in which the generated images are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated.

=cut

has 'response_format' => (
    is       => 'ro',
    isa      => Enum[
        "url",
        "b64_json",
    ],
);

=head2 C<< size >>

The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`. Must be one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3` models.

=cut

has 'size' => (
    is       => 'ro',
    isa      => Enum[
        "256x256",
        "512x512",
        "1024x1024",
        "1792x1024",
        "1024x1792",
    ],
);

=head2 C<< style >>

The style of the generated images. Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images. This param is only supported for `dall-e-3`.

=cut

has 'style' => (
    is       => 'ro',
    isa      => Enum[
        "vivid",
        "natural",
    ],
);

=head2 C<< user >>

A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).

=cut

has 'user' => (
    is       => 'ro',
    isa      => Str,
);


1;
