package AI::OpenAI::CreateTranslationRequest 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

AI::OpenAI::CreateTranslationRequest -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::CreateTranslationRequest->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< file >>

The audio file object (not file name) translate, in one of these formats: flac, mp3, mp4, mpeg, mpga, m4a, ogg, wav, or webm.

=cut

has 'file' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< model >>

ID of the model to use. Only `whisper-1` (which is powered by our open source Whisper V2 model) is currently available.

=cut

has 'model' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< prompt >>

An optional text to guide the model's style or continue a previous audio segment. The [prompt](/docs/guides/speech-to-text/prompting) should be in English.

=cut

has 'prompt' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< response_format >>

The format of the transcript output, in one of these options: `json`, `text`, `srt`, `verbose_json`, or `vtt`.

=cut

has 'response_format' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< temperature >>

The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. If set to 0, the model will use [log probability](https://en.wikipedia.org/wiki/Log_probability) to automatically increase the temperature until certain thresholds are hit.

=cut

has 'temperature' => (
    is       => 'ro',
    isa      => Num,
);


1;
