package AI::OpenAI::CreateFileRequest 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

AI::OpenAI::CreateFileRequest -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::CreateFileRequest->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< file >>

The File object (not file name) to be uploaded.

=cut

has 'file' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< purpose >>

The intended purpose of the uploaded file.

Use "assistants" for [Assistants](/docs/api-reference/assistants) and [Message](/docs/api-reference/messages) files, "vision" for Assistants image file inputs, "batch" for [Batch API](/docs/guides/batch), and "fine-tune" for [Fine-tuning](/docs/api-reference/fine-tuning).

=cut

has 'purpose' => (
    is       => 'ro',
    isa      => Enum[
        "assistants",
        "batch",
        "fine-tune",
    ],
    required => 1,
);


1;
