package AI::OpenAI::CreateRunRequest 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::CreateRunRequest -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::CreateRunRequest->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< additional_instructions >>

Appends additional instructions at the end of the instructions for the run. This is useful for modifying the behavior on a per-run basis without overriding other instructions.

=cut

has 'additional_instructions' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< additional_messages >>

Adds additional messages to the thread before creating the run.

=cut

has 'additional_messages' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
);

=head2 C<< assistant_id >>

The ID of the [assistant](/docs/api-reference/assistants) to use to execute this run.

=cut

has 'assistant_id' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< instructions >>

Overrides the [instructions](/docs/api-reference/assistants/createAssistant) of the assistant. This is useful for modifying the behavior on a per-run basis.

=cut

has 'instructions' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< max_completion_tokens >>

The maximum number of completion tokens that may be used over the course of the run. The run will make a best effort to use only the number of completion tokens specified, across multiple turns of the run. If the run exceeds the number of completion tokens specified, the run will end with status `incomplete`. See `incomplete_details` for more info.

=cut

has 'max_completion_tokens' => (
    is       => 'ro',
    isa      => Int,
);

=head2 C<< max_prompt_tokens >>

The maximum number of prompt tokens that may be used over the course of the run. The run will make a best effort to use only the number of prompt tokens specified, across multiple turns of the run. If the run exceeds the number of prompt tokens specified, the run will end with status `incomplete`. See `incomplete_details` for more info.

=cut

has 'max_prompt_tokens' => (
    is       => 'ro',
    isa      => Int,
);

=head2 C<< metadata >>

Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.

=cut

has 'metadata' => (
    is       => 'ro',
    isa      => HashRef,
);

=head2 C<< model >>

The ID of the [Model](/docs/api-reference/models) to be used to execute this run. If a value is provided here, it will override the model associated with the assistant. If not, the model associated with the assistant will be used.

=cut

has 'model' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< response_format >>

Specifies the format that the model must output. Compatible with [GPT-4o](/docs/models/gpt-4o), [GPT-4 Turbo](/docs/models/gpt-4-turbo-and-gpt-4), and all GPT-3.5 Turbo models since `gpt-3.5-turbo-1106`.

Setting to `{ "type": "json_object" }` enables JSON mode, which guarantees the message the model generates is valid JSON.

**Important:** when using JSON mode, you **must** also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly "stuck" request. Also note that the message content may be partially cut off if `finish_reason="length"`, which indicates the generation exceeded `max_tokens` or the conversation exceeded the max context length.

=cut

has 'response_format' => (
    is       => 'ro',
);

=head2 C<< stream >>

If `true`, returns a stream of events that happen during the Run as server-sent events, terminating when the Run enters a terminal state with a `data: [DONE]` message.

=cut

has 'stream' => (
    is       => 'ro',
);

=head2 C<< temperature >>

What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.

=cut

has 'temperature' => (
    is       => 'ro',
    isa      => Num,
);

=head2 C<< tool_choice >>

Controls which (if any) tool is called by the model.
`none` means the model will not call any tools and instead generates a message.
`auto` is the default value and means the model can pick between generating a message or calling one or more tools.
`required` means the model must call one or more tools before responding to the user.
Specifying a particular tool like `{"type": "file_search"}` or `{"type": "function", "function": {"name": "my_function"}}` forces the model to call that tool.

=cut

has 'tool_choice' => (
    is       => 'ro',
);

=head2 C<< tools >>

Override the tools the assistant can use for this run. This is useful for modifying the behavior on a per-run basis.

=cut

has 'tools' => (
    is       => 'ro',
    isa      => ArrayRef[],
);

=head2 C<< top_p >>

An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.

We generally recommend altering this or temperature but not both.

=cut

has 'top_p' => (
    is       => 'ro',
    isa      => Num,
);

=head2 C<< truncation_strategy >>

Controls for how a thread will be truncated prior to the run. Use this to control the intial context window of the run.

=cut

has 'truncation_strategy' => (
    is       => 'ro',
    isa      => HashRef,
);


1;
