package AI::OpenAI::Error 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::Error -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::Error->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< code >>

=cut

has 'code' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< message >>

=cut

has 'message' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< param >>

=cut

has 'param' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< type >>

=cut

has 'type' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);


1;
