package AI::OpenAI::FineTuningJobEvent 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::FineTuningJobEvent -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::FineTuningJobEvent->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< created_at >>

=cut

has 'created_at' => (
    is       => 'ro',
    isa      => Int,
    required => 1,
);

=head2 C<< id >>

=cut

has 'id' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< level >>

=cut

has 'level' => (
    is       => 'ro',
    isa      => Enum[
        "info",
        "warn",
        "error",
    ],
    required => 1,
);

=head2 C<< message >>

=cut

has 'message' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< object >>

=cut

has 'object' => (
    is       => 'ro',
    isa      => Enum[
        "fine_tuning.job.event",
    ],
    required => 1,
);


1;
