package AI::OpenAI::MessageDeltaContentTextObject 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::MessageDeltaContentTextObject -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::MessageDeltaContentTextObject->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< index >>

The index of the content part in the message.

=cut

has 'index' => (
    is       => 'ro',
    isa      => Int,
    required => 1,
);

=head2 C<< text >>

=cut

has 'text' => (
    is       => 'ro',
    isa      => HashRef,
);

=head2 C<< type >>

Always `text`.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "text",
    ],
    required => 1,
);


1;
