package AI::OpenAI::MessageContentImageFileObject 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::MessageContentImageFileObject -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::MessageContentImageFileObject->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< image_file >>

=cut

has 'image_file' => (
    is       => 'ro',
    isa      => HashRef,
    required => 1,
);

=head2 C<< type >>

Always `image_file`.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "image_file",
    ],
    required => 1,
);


1;
