package AI::OpenAI::MessageDeltaContentImageUrlObject 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

AI::OpenAI::MessageDeltaContentImageUrlObject -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::MessageDeltaContentImageUrlObject->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< image_url >>

=cut

has 'image_url' => (
    is       => 'ro',
    isa      => HashRef,
);

=head2 C<< index >>

The index of the content part in the message.

=cut

has 'index' => (
    is       => 'ro',
    isa      => Int,
    required => 1,
);

=head2 C<< type >>

Always `image_url`.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "image_url",
    ],
    required => 1,
);


1;
