package AI::OpenAI::MessageDeltaObject 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=encoding utf8

=head1 NAME

AI::OpenAI::MessageDeltaObject -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::MessageDeltaObject->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< delta >>

The delta containing the fields that have changed on the Message.

=cut

has 'delta' => (
    is       => 'ro',
    isa      => HashRef,
    required => 1,
);

=head2 C<< id >>

The identifier of the message, which can be referenced in API endpoints.

=cut

has 'id' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< object >>

The object type, which is always `thread.message.delta`.

=cut

has 'object' => (
    is       => 'ro',
    isa      => Enum[
        "thread.message.delta",
    ],
    required => 1,
);


1;
