package AI::OpenAI::MessageDeltaContentTextAnnotationsFileCitationObject 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

AI::OpenAI::MessageDeltaContentTextAnnotationsFileCitationObject -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::MessageDeltaContentTextAnnotationsFileCitationObject->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< end_index >>

=cut

has 'end_index' => (
    is       => 'ro',
    isa      => Int,
);

=head2 C<< file_citation >>

=cut

has 'file_citation' => (
    is       => 'ro',
    isa      => HashRef,
);

=head2 C<< index >>

The index of the annotation in the text content part.

=cut

has 'index' => (
    is       => 'ro',
    isa      => Int,
    required => 1,
);

=head2 C<< start_index >>

=cut

has 'start_index' => (
    is       => 'ro',
    isa      => Int,
);

=head2 C<< text >>

The text in the message content that needs to be replaced.

=cut

has 'text' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< type >>

Always `file_citation`.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "file_citation",
    ],
    required => 1,
);


1;
