package AI::OpenAI::RunStepDetailsToolCallsFileSearchObject 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::RunStepDetailsToolCallsFileSearchObject -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::RunStepDetailsToolCallsFileSearchObject->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< file_search >>

For now, this is always going to be an empty object.

=cut

has 'file_search' => (
    is       => 'ro',
    isa      => HashRef,
    required => 1,
);

=head2 C<< id >>

The ID of the tool call object.

=cut

has 'id' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< type >>

The type of tool call. This is always going to be `file_search` for this type of tool call.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "file_search",
    ],
    required => 1,
);


1;
