package AI::OpenAI::RunStepDeltaStepDetailsMessageCreationObject 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::RunStepDeltaStepDetailsMessageCreationObject -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::RunStepDeltaStepDetailsMessageCreationObject->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< message_creation >>

=cut

has 'message_creation' => (
    is       => 'ro',
    isa      => HashRef,
);

=head2 C<< type >>

Always `message_creation`.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "message_creation",
    ],
    required => 1,
);


1;
