package AI::OpenAI::RunStepDeltaStepDetailsToolCallsObject 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::RunStepDeltaStepDetailsToolCallsObject -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::RunStepDeltaStepDetailsToolCallsObject->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< tool_calls >>

An array of tool calls the run step was involved in. These can be associated with one of three types of tools: `code_interpreter`, `file_search`, or `function`.

=cut

has 'tool_calls' => (
    is       => 'ro',
    isa      => ArrayRef[],
);

=head2 C<< type >>

Always `tool_calls`.

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "tool_calls",
    ],
    required => 1,
);


1;
