package AI::OpenAI::SubmitToolOutputsRunRequest 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::SubmitToolOutputsRunRequest -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::SubmitToolOutputsRunRequest->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< stream >>

If `true`, returns a stream of events that happen during the Run as server-sent events, terminating when the Run enters a terminal state with a `data: [DONE]` message.

=cut

has 'stream' => (
    is       => 'ro',
);

=head2 C<< tool_outputs >>

A list of tools for which the outputs are being submitted.

=cut

has 'tool_outputs' => (
    is       => 'ro',
    isa      => ArrayRef[HashRef],
    required => 1,
);


1;
