package AI::OpenAI::VectorStoreExpirationAfter 0.01;
# DO NOT EDIT! This is an autogenerated file.

use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

use namespace::clean;

=encoding utf8

=head1 NAME

AI::OpenAI::VectorStoreExpirationAfter -

=head1 SYNOPSIS

  my $obj = AI::OpenAI::VectorStoreExpirationAfter->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< anchor >>

Anchor timestamp after which the expiration policy applies. Supported anchors: `last_active_at`.

=cut

has 'anchor' => (
    is       => 'ro',
    isa      => Enum[
        "last_active_at",
    ],
    required => 1,
);

=head2 C<< days >>

The number of days after the anchor time that the vector store will expire.

=cut

has 'days' => (
    is       => 'ro',
    isa      => Int,
    required => 1,
);


1;
