package AI::OpenAPI::AssistantToolsFunction 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

AI::OpenAPI::AssistantToolsFunction -

=head1 SYNOPSIS

  my $obj = AI::OpenAPI::AssistantToolsFunction->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< function >>

=cut

has 'function' => (
    is       => 'ro',
    isa      => HashRef,
    required => 1,
);

=head2 C<< type >>

The type of tool being defined: `function`

=cut

has 'type' => (
    is       => 'ro',
    isa      => Enum[
        "function",
    ],
    required => 1,
);


1;
