package AI::OpenAPI::BatchRequestInput 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

AI::OpenAPI::BatchRequestInput -

=head1 SYNOPSIS

  my $obj = AI::OpenAPI::BatchRequestInput->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< custom_id >>

A developer-provided per-request id that will be used to match outputs to inputs. Must be unique for each request in a batch.

=cut

has 'custom_id' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< method >>

The HTTP method to be used for the request. Currently only `POST` is supported.

=cut

has 'method' => (
    is       => 'ro',
    isa      => Enum[
        "POST",
    ],
);

=head2 C<< url >>

The OpenAI API relative URL to be used for the request. Currently `/v1/chat/completions`, `/v1/embeddings`, and `/v1/completions` are supported.

=cut

has 'url' => (
    is       => 'ro',
    isa      => Str,
);


1;
