package AI::OpenAPI::BatchRequestOutput 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use stable 'postderef';
use Types::Standard qw(Enum Str Bool Num Int HashRef ArrayRef);
use MooX::TypeTiny;

=head1 NAME

AI::OpenAPI::BatchRequestOutput -

=head1 SYNOPSIS

  my $obj = AI::OpenAPI::BatchRequestOutput->new();
  ...

=cut

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< custom_id >>

A developer-provided per-request id that will be used to match outputs to inputs.

=cut

has 'custom_id' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< error >>

For requests that failed with a non-HTTP error, this will contain more information on the cause of the failure.

=cut

has 'error' => (
    is       => 'ro',
    isa      => HashRef,
);

=head2 C<< id >>

=cut

has 'id' => (
    is       => 'ro',
    isa      => Str,
);

=head2 C<< response >>

=cut

has 'response' => (
    is       => 'ro',
    isa      => HashRef,
);


1;
