package Speech::Recognition::Whisper::User 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';
use Types::Standard qw(Str Bool Num Int Object ArrayRef);
use MooX::TypeTiny;

sub as_hash( $self ) {
    return { $self->%* }
}

=head1 PROPERTIES

=head2 C<< email >>

=cut

has 'email' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< password >>

=cut

has 'password' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);

=head2 C<< username >>

=cut

has 'username' => (
    is       => 'ro',
    isa      => Str,
    required => 1,
);


1;
